version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - build:
          name: Run tests
          command: npm run build

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
